version: "3.9"

services:
  fastapi:
    container_name: fastapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./dockerfiles/fastapi/Dockerfile
    expose:
      - 8080
    depends_on:
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             bash gunicorn.sh"
    networks:
      - nginx_network
      - db_network
    environment:
      PG_NAME: postgres
      PG_USER: postgres
      PG_HOST: db
      PG_PORT: "5432"
      PG_PASSWORD: postgres

  db:
    container_name: db
    image: postgres:16.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA =/var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - .:/docker-entrypoint-initdb.d
    expose:
      - 5432
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./dockerfiles/react/Dockerfile
    ports:
      - 80:80
    depends_on:
      - fastapi
    networks:
      - nginx_network

volumes:
  postgres-data:

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge